name       : catfish
version    : 1.4.5
release    : 4
source     :
    - https://launchpad.net/catfish-search/1.4/1.4.5/+download/catfish-1.4.5.tar.gz : ad2304561b6eb0dea7c230241428f1017122fba403657d03a70e1f1ddc752c37
license    : GPL-2.0
component  : desktop
summary    : Versatile filesearching tool
description: |
    Catfish is a search GUI powered by locate and find behind the scenes, with autocompletion from Zeitgeist and locate. The advanced options allow filtering by date and file type. The interface is intentionally lightweight and simple, using only GTK+.
builddeps  :
    - python-distutils-extra
    - python-gobject-devel
    - python-pexpect
    - python-setuptools
rundeps    :
    - python-pexpect
setup      : |
    %python_setup
install    : |
    %python_install

