name       : catfish
version    : 1.4.10
release    : 5
source     :
    - https://archive.xfce.org/src/apps/catfish/1.4/catfish-1.4.10.tar.bz2 : 2573a004105031f871c92fed22a0c4b15bb96f2dff6e36c4f2959f56b62e343d
license    : GPL-2.0-or-later
component  : desktop
summary    : Versatile file searching tool
description: |
    Catfish is a search GUI powered by locate and find behind the scenes, with autocompletion from Zeitgeist and locate. The advanced options allow filtering by date and file type. The interface is intentionally lightweight and simple, using only GTK+3. You can configure it to your needs by using several command line options.
builddeps  :
    - python-distutils-extra
rundeps    :
    - python3-cairo
    - python-pexpect
setup      : |
    %python3_setup
install    : |
    %python3_install
