name       : catfish
version    : 4.18.0
release    : 14
source     :
    - https://archive.xfce.org/src/apps/catfish/4.18/catfish-4.18.0.tar.bz2 : fdae9b73cc754a50716bb04b958aa31dbd7e94047068b7207f2ae313a7d58b99
homepage   : https://docs.xfce.org/apps/catfish/start
license    : GPL-2.0-or-later
component  : desktop
summary    : Versatile file searching tool
description: |
    Catfish is a search GUI powered by locate and find behind the scenes, with autocompletion from Zeitgeist and locate. The advanced options allow filtering by date and file type. The interface is intentionally lightweight and simple, using only GTK+3. You can configure it to your needs by using several command line options.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - python-distutils-extra
rundeps    :
    - python-pexpect
    - python3-cairo
    - xfconf
setup      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc
