name       : catfish
version    : 1.4.4
release    : 3
source     :
    - https://launchpad.net/catfish-search/1.4/1.4.4/+download/catfish-1.4.4.tar.gz : a2d452780bf51f80afe7621e040fe77725021c24a0fe4a9744c89ba88dbf87d7
license    : GPL-2.0
component  : desktop
summary    : Versatile filesearching tool
description: |
    Catfish is a search GUI powered by locate and find behind the scenes, with autocompletion from Zeitgeist and locate. The advanced options allow filtering by date and file type. The interface is intentionally lightweight and simple, using only GTK+.
builddeps  :
    - python-distutils-extra
    - python-gobject-devel
    - python-pexpect
    - python-setuptools
rundeps    :
    - python-pexpect
setup      : |
    %python_setup
install    : |
    %python_install

