name       : catfish
version    : 1.4.12
release    : 7
source     :
    - https://archive.xfce.org/src/apps/catfish/1.4/catfish-1.4.12.tar.bz2 : c3fb30e02b217752aa493b49769be1a5fc2adde70b22aef381e6c67d5227134a
homepage   : https://docs.xfce.org/apps/catfish/start
license    : GPL-2.0-or-later
component  : desktop
summary    : Versatile file searching tool
description: |
    Catfish is a search GUI powered by locate and find behind the scenes, with autocompletion from Zeitgeist and locate. The advanced options allow filtering by date and file type. The interface is intentionally lightweight and simple, using only GTK+3. You can configure it to your needs by using several command line options.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - python-distutils-extra
rundeps    :
    - python3-cairo
    - python-pexpect
setup      : |
    %python3_setup
install    : |
    %python3_install
